# Generated by Django 2.2 on 2020-06-07 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_reviews'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Reviews',
            new_name='Review',
        ),
    ]
