# Generated by Django 2.2 on 2020-09-10 10:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20200910_1017'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='review_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 10, 10, 30, 47, 527046), verbose_name='date published'),
        ),
    ]
