# Generated by Django 2.2 on 2020-09-10 11:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_review_review_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorie',
            name='category_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 10, 11, 2, 58, 26001), verbose_name='date published'),
        ),
        migrations.AddField(
            model_name='team',
            name='team_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 10, 11, 2, 58, 26465), verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='review',
            name='review_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 10, 11, 2, 58, 25477), verbose_name='date published'),
        ),
        migrations.DeleteModel(
            name='Item',
        ),
        migrations.DeleteModel(
            name='ToDoList',
        ),
    ]
